// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"
	"errors"
	"math/big"

	"github.com/morph-l2/go-ethereum/common"
	"github.com/morph-l2/go-ethereum/common/hexutil"
)

var _ = (*receiptMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (r Receipt) MarshalJSON() ([]byte, error) {
	type Receipt struct {
		Type              hexutil.Uint64    `json:"type,omitempty"`
		PostState         hexutil.Bytes     `json:"root"`
		Status            hexutil.Uint64    `json:"status"`
		CumulativeGasUsed hexutil.Uint64    `json:"cumulativeGasUsed" gencodec:"required"`
		Bloom             Bloom             `json:"logsBloom"         gencodec:"required"`
		Logs              []*Log            `json:"logs"              gencodec:"required"`
		TxHash            common.Hash       `json:"transactionHash" gencodec:"required"`
		ContractAddress   common.Address    `json:"contractAddress"`
		GasUsed           hexutil.Uint64    `json:"gasUsed" gencodec:"required"`
		EffectiveGasPrice *hexutil.Big      `json:"effectiveGasPrice"`
		BlobGasUsed       hexutil.Uint64    `json:"blobGasUsed,omitempty"`
		BlobGasPrice      *hexutil.Big      `json:"blobGasPrice,omitempty"`
		BlockHash         common.Hash       `json:"blockHash,omitempty"`
		BlockNumber       *hexutil.Big      `json:"blockNumber,omitempty"`
		TransactionIndex  hexutil.Uint      `json:"transactionIndex"`
		ReturnValue       []byte            `json:"returnValue,omitempty"`
		L1Fee             *hexutil.Big      `json:"l1Fee,omitempty"`
		FeeTokenID        *hexutil.Uint16   `json:"feeTokenID,omitempty"`
		FeeRate           *hexutil.Big      `json:"feeRate,omitempty"`
		TokenScale        *hexutil.Big      `json:"tokenScale,omitempty"`
		FeeLimit          *hexutil.Big      `json:"feeLimit,omitempty"`
		Version           hexutil.Uint64    `json:"version,omitempty"`
		Reference         *common.Reference `json:"reference,omitempty"`
		Memo              *hexutil.Bytes    `json:"memo,omitempty"`
	}
	var enc Receipt
	enc.Type = hexutil.Uint64(r.Type)
	enc.PostState = r.PostState
	enc.Status = hexutil.Uint64(r.Status)
	enc.CumulativeGasUsed = hexutil.Uint64(r.CumulativeGasUsed)
	enc.Bloom = r.Bloom
	enc.Logs = r.Logs
	enc.TxHash = r.TxHash
	enc.ContractAddress = r.ContractAddress
	enc.GasUsed = hexutil.Uint64(r.GasUsed)
	enc.EffectiveGasPrice = (*hexutil.Big)(r.EffectiveGasPrice)
	enc.BlobGasUsed = hexutil.Uint64(r.BlobGasUsed)
	enc.BlobGasPrice = (*hexutil.Big)(r.BlobGasPrice)
	enc.BlockHash = r.BlockHash
	enc.BlockNumber = (*hexutil.Big)(r.BlockNumber)
	enc.TransactionIndex = hexutil.Uint(r.TransactionIndex)
	enc.ReturnValue = r.ReturnValue
	enc.L1Fee = (*hexutil.Big)(r.L1Fee)
	enc.FeeTokenID = (*hexutil.Uint16)(r.FeeTokenID)
	enc.FeeRate = (*hexutil.Big)(r.FeeRate)
	enc.TokenScale = (*hexutil.Big)(r.TokenScale)
	enc.FeeLimit = (*hexutil.Big)(r.FeeLimit)
	enc.Version = hexutil.Uint64(r.Version)
	enc.Reference = r.Reference
	enc.Memo = (*hexutil.Bytes)(r.Memo)
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (r *Receipt) UnmarshalJSON(input []byte) error {
	type Receipt struct {
		Type              *hexutil.Uint64   `json:"type,omitempty"`
		PostState         *hexutil.Bytes    `json:"root"`
		Status            *hexutil.Uint64   `json:"status"`
		CumulativeGasUsed *hexutil.Uint64   `json:"cumulativeGasUsed" gencodec:"required"`
		Bloom             *Bloom            `json:"logsBloom"         gencodec:"required"`
		Logs              []*Log            `json:"logs"              gencodec:"required"`
		TxHash            *common.Hash      `json:"transactionHash" gencodec:"required"`
		ContractAddress   *common.Address   `json:"contractAddress"`
		GasUsed           *hexutil.Uint64   `json:"gasUsed" gencodec:"required"`
		EffectiveGasPrice *hexutil.Big      `json:"effectiveGasPrice"`
		BlobGasUsed       *hexutil.Uint64   `json:"blobGasUsed,omitempty"`
		BlobGasPrice      *hexutil.Big      `json:"blobGasPrice,omitempty"`
		BlockHash         *common.Hash      `json:"blockHash,omitempty"`
		BlockNumber       *hexutil.Big      `json:"blockNumber,omitempty"`
		TransactionIndex  *hexutil.Uint     `json:"transactionIndex"`
		ReturnValue       []byte            `json:"returnValue,omitempty"`
		L1Fee             *hexutil.Big      `json:"l1Fee,omitempty"`
		FeeTokenID        *hexutil.Uint16   `json:"feeTokenID,omitempty"`
		FeeRate           *hexutil.Big      `json:"feeRate,omitempty"`
		TokenScale        *hexutil.Big      `json:"tokenScale,omitempty"`
		FeeLimit          *hexutil.Big      `json:"feeLimit,omitempty"`
		Version           *hexutil.Uint64   `json:"version,omitempty"`
		Reference         *common.Reference `json:"reference,omitempty"`
		Memo              *hexutil.Bytes    `json:"memo,omitempty"`
	}
	var dec Receipt
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Type != nil {
		r.Type = uint8(*dec.Type)
	}
	if dec.PostState != nil {
		r.PostState = *dec.PostState
	}
	if dec.Status != nil {
		r.Status = uint64(*dec.Status)
	}
	if dec.CumulativeGasUsed == nil {
		return errors.New("missing required field 'cumulativeGasUsed' for Receipt")
	}
	r.CumulativeGasUsed = uint64(*dec.CumulativeGasUsed)
	if dec.Bloom == nil {
		return errors.New("missing required field 'logsBloom' for Receipt")
	}
	r.Bloom = *dec.Bloom
	if dec.Logs == nil {
		return errors.New("missing required field 'logs' for Receipt")
	}
	r.Logs = dec.Logs
	if dec.TxHash == nil {
		return errors.New("missing required field 'transactionHash' for Receipt")
	}
	r.TxHash = *dec.TxHash
	if dec.ContractAddress != nil {
		r.ContractAddress = *dec.ContractAddress
	}
	if dec.GasUsed == nil {
		return errors.New("missing required field 'gasUsed' for Receipt")
	}
	r.GasUsed = uint64(*dec.GasUsed)
	if dec.EffectiveGasPrice != nil {
		r.EffectiveGasPrice = (*big.Int)(dec.EffectiveGasPrice)
	}
	if dec.BlobGasUsed != nil {
		r.BlobGasUsed = uint64(*dec.BlobGasUsed)
	}
	if dec.BlobGasPrice != nil {
		r.BlobGasPrice = (*big.Int)(dec.BlobGasPrice)
	}
	if dec.BlockHash != nil {
		r.BlockHash = *dec.BlockHash
	}
	if dec.BlockNumber != nil {
		r.BlockNumber = (*big.Int)(dec.BlockNumber)
	}
	if dec.TransactionIndex != nil {
		r.TransactionIndex = uint(*dec.TransactionIndex)
	}
	if dec.ReturnValue != nil {
		r.ReturnValue = dec.ReturnValue
	}
	if dec.L1Fee != nil {
		r.L1Fee = (*big.Int)(dec.L1Fee)
	}
	if dec.FeeTokenID != nil {
		r.FeeTokenID = (*uint16)(dec.FeeTokenID)
	}
	if dec.FeeRate != nil {
		r.FeeRate = (*big.Int)(dec.FeeRate)
	}
	if dec.TokenScale != nil {
		r.TokenScale = (*big.Int)(dec.TokenScale)
	}
	if dec.FeeLimit != nil {
		r.FeeLimit = (*big.Int)(dec.FeeLimit)
	}
	if dec.Version != nil {
		r.Version = uint8(*dec.Version)
	}
	if dec.Reference != nil {
		r.Reference = dec.Reference
	}
	if dec.Memo != nil {
		r.Memo = (*[]byte)(dec.Memo)
	}
	return nil
}
