// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package catalyst

import (
	"encoding/json"
	"errors"

	"github.com/scroll-tech/go-ethereum/common/hexutil"
)

var _ = (*assembleL2BlockParamsMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (a AssembleL2BlockParams) MarshalJSON() ([]byte, error) {
	type AssembleL2BlockParams struct {
		Number hexutil.Uint64 `json:"number"        gencodec:"required"`
	}
	var enc AssembleL2BlockParams
	enc.Number = hexutil.Uint64(a.Number)
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (a *AssembleL2BlockParams) UnmarshalJSON(input []byte) error {
	type AssembleL2BlockParams struct {
		Number *hexutil.Uint64 `json:"number"        gencodec:"required"`
	}
	var dec AssembleL2BlockParams
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Number == nil {
		return errors.New("missing required field 'number' for AssembleL2BlockParams")
	}
	a.Number = uint64(*dec.Number)
	return nil
}
