// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package catalyst

import (
	"encoding/json"
	"errors"

	"github.com/morph-l2/go-ethereum/common"
	"github.com/morph-l2/go-ethereum/common/hexutil"
)

var _ = (*assembleL2BlockV2ParamsMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (a AssembleL2BlockV2Params) MarshalJSON() ([]byte, error) {
	type AssembleL2BlockV2Params struct {
		ParentHash   common.Hash     `json:"parentHash"    gencodec:"required"`
		Transactions []hexutil.Bytes `json:"transactions"`
		Timestamp    *hexutil.Uint64 `json:"timestamp"`
	}
	var enc AssembleL2BlockV2Params
	enc.ParentHash = a.ParentHash
	if a.Transactions != nil {
		enc.Transactions = make([]hexutil.Bytes, len(a.Transactions))
		for k, v := range a.Transactions {
			enc.Transactions[k] = v
		}
	}
	enc.Timestamp = (*hexutil.Uint64)(a.Timestamp)
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (a *AssembleL2BlockV2Params) UnmarshalJSON(input []byte) error {
	type AssembleL2BlockV2Params struct {
		ParentHash   *common.Hash    `json:"parentHash"    gencodec:"required"`
		Transactions []hexutil.Bytes `json:"transactions"`
		Timestamp    *hexutil.Uint64 `json:"timestamp"`
	}
	var dec AssembleL2BlockV2Params
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.ParentHash == nil {
		return errors.New("missing required field 'parentHash' for AssembleL2BlockV2Params")
	}
	a.ParentHash = *dec.ParentHash
	if dec.Transactions != nil {
		a.Transactions = make([][]byte, len(dec.Transactions))
		for k, v := range dec.Transactions {
			a.Transactions[k] = v
		}
	}
	if dec.Timestamp != nil {
		a.Timestamp = (*uint64)(dec.Timestamp)
	}
	return nil
}
