version: '3.4'

volumes:
  morph_data_0:
  morph_data_1:
  morph_data_2:
  morph_data_3:

services:
  morph-geth-0:
    build:
      context: ..
      dockerfile: ./Dockerfile
    image: morph_geth:latest
    ports:
      - "8545:8545"
      - "8546:8546"
      - "8551:8551"
      - "30303"
    volumes:
      - "morph_data_0:/db"
      - "${PWD}/build/jwt-secret.txt:/config/jwt-secret.txt"
      - "${PWD}/genesis_l2.json:/genesis.json"
      - "${PWD}/testnet/nodekey:/db/geth/nodekey"
    entrypoint: # always use this nodekey, in order to keep the encoded node ID the same
      - "/bin/sh"
      - "/entrypoint.sh"

  morph-geth-1:
    depends_on:
      - morph-geth-0
    build:
      context: ..
      dockerfile: ./Dockerfile
    image: morph_geth:latest
    ports:
      - "8645:8545"
      - "8646:8546"
      - "8651:8551"
      - "30303"
    volumes:
      - "morph_data_1:/db"
      - "${PWD}/build/jwt-secret.txt:/config/jwt-secret.txt"
      - "${PWD}/genesis_l2.json:/genesis.json"
      - "${PWD}/testnet/static-nodes.json:/db/geth/static-nodes.json"
    environment:
      - BOOT_NODES=enode://58e698ea2dd8a76e0cb185d13c1faabf223b60c89fef988c8b89496571056d6c2922109537bb291cd87f2ec09a23ac37d59bde2c7a4885d07b7b641cadff2921@morph-geth-0:30303
    entrypoint: # pass the L2 specific flags by overriding the entry-point and adding extra arguments
      - "/bin/sh"
      - "/entrypoint.sh"

  morph-geth-2:
    depends_on:
      - morph-geth-0
    build:
      context: ..
      dockerfile: ./Dockerfile
    image: morph_geth:latest
    ports:
      - "8745:8545"
      - "8746:8546"
      - "8751:8551"
      - "30303"
    volumes:
      - "morph_data_2:/db"
      - "${PWD}/build/jwt-secret.txt:/config/jwt-secret.txt"
      - "${PWD}/genesis_l2.json:/genesis.json"
      - "${PWD}/testnet/static-nodes.json:/db/geth/static-nodes.json"
    environment:
      - BOOT_NODES=enode://58e698ea2dd8a76e0cb185d13c1faabf223b60c89fef988c8b89496571056d6c2922109537bb291cd87f2ec09a23ac37d59bde2c7a4885d07b7b641cadff2921@morph-geth-0:30303
    entrypoint: # pass the L2 specific flags by overriding the entry-point and adding extra arguments
      - "/bin/sh"
      - "/entrypoint.sh"

  morph-geth-3:
    depends_on:
      - morph-geth-0
    build:
      context: ..
      dockerfile: ./Dockerfile
    image: morph_geth:latest
    ports:
      - "8845:8545"
      - "8846:8546"
      - "8851:8551"
      - "30303"
    volumes:
      - "morph_data_3:/db"
      - "${PWD}/build/jwt-secret.txt:/config/jwt-secret.txt"
      - "${PWD}/genesis_l2.json:/genesis.json"
      - "${PWD}/testnet/static-nodes.json:/db/geth/static-nodes.json"
    environment:
      - BOOT_NODES=enode://58e698ea2dd8a76e0cb185d13c1faabf223b60c89fef988c8b89496571056d6c2922109537bb291cd87f2ec09a23ac37d59bde2c7a4885d07b7b641cadff2921@morph-geth-0:30303
    entrypoint: # pass the L2 specific flags by overriding the entry-point and adding extra arguments
      - "/bin/sh"
      - "/entrypoint.sh"
