on:
  pull_request:
    branches:
      - main
    types: ["closed"]

jobs:
  cherry_pick_release_0_3_x:
    runs-on: ubuntu-latest
    name: Cherry pick into release/0.3.x
    if: ${{ contains(github.event.pull_request.labels.*.name, 'release/0.3.x') && github.event.pull_request.merged == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cherry pick into release/0.3.x
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
        with:
          branch: release/0.3.x
          labels: |
            cherry-pick

  cherry_pick_release_0_4_x:
    runs-on: ubuntu-latest
    name: Cherry pick into release/0.4.x
    if: ${{ contains(github.event.pull_request.labels.*.name, 'release/0.4.x') && github.event.pull_request.merged == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cherry pick into release/0.4.x
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
        with:
          branch: release/0.4.x
          labels: |
            cherry-pick

  cherry_pick_release_0_5_x:
    runs-on: ubuntu-latest
    name: Cherry pick into release/0.5.x
    if: ${{ contains(github.event.pull_request.labels.*.name, 'release/0.5.x') && github.event.pull_request.merged == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cherry pick into release/0.5.x
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
        with:
          branch: release/0.5.x
          labels: |
            cherry-pick

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}